sudo: required
services:
  - docker

before_install:
  - docker build -t konradgalczynski07/client-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true konradgalczynski07/client-test npm run test

after_success:
  - docker build -t konradgalczynski07/client ./client
  - docker build -t konradgalczynski07/nginx ./nginx
  - docker build -t konradgalczynski07/server ./server
  - docker build -t konradgalczynski07/worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push konradgalczynski07/client
  - docker push konradgalczynski07/nginx
  - docker push konradgalczynski07/server
  - docker push konradgalczynski07/worker
