sudo: required
services:
  - docker

before_install:
  - docker build -t konrad/multi-docker -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true konrad/multi-docker npm run test

after_success:
  - docker build -t konrad/client ./client
  - docker build -t konrad/nginx ./nginx
  - docker build -t konrad/server ./server
  - docker build -t konrad/worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push konrad/client
  - docker push konrad/nginx
  - docker push konrad/server
  - docker push konrad/worker
