sudo: required
services:
  - docker

before_install:
  - docker build -t konradgalczynski07/client-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true konradgalczynski07/client-test npm run test

after_success:
  - docker build -t konradgalczynski07/client ./client
  - docker build -t konradgalczynski07/nginx ./nginx
  - docker build -t konradgalczynski07/server ./server
  - docker build -t konradgalczynski07/worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push konradgalczynski07/client
  - docker push konradgalczynski07/nginx
  - docker push konradgalczynski07/server
  - docker push konradgalczynski07/worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket-name: "elasticbeanstalk-eu-central-1-630211744078"
  bucket_path: "multi-docker"
  edge: true
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"